// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ShoppingCartService/internal/biz"
	"ShoppingCartService/internal/conf"
	"ShoppingCartService/internal/data"
	"ShoppingCartService/internal/registry"
	"ShoppingCartService/internal/server"
	"ShoppingCartService/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, mysql *conf.Mysql, etcd *conf.Etcd, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(mysql, logger)
	if err != nil {
		return nil, nil, err
	}
	cartRepo := data.NewCartRepo(dataData, logger)
	cartUsecase := biz.NewCartUsecase(cartRepo, logger)
	cartService := service.NewGreeterService(cartUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, cartService, logger)
	httpServer := server.NewHTTPServer(confServer, cartService, logger)
	etcdRegistry := registry.NewRegistrarServer(etcd)
	app := newApp(logger, grpcServer, httpServer, etcdRegistry)
	return app, func() {
		cleanup()
	}, nil
}
