// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v3.21.6
// source: cart/v1/cart.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCartAddCommodity = "/helloworld.v1.Cart/AddCommodity"
const OperationCartClearCart = "/helloworld.v1.Cart/ClearCart"
const OperationCartDeleteCommodity = "/helloworld.v1.Cart/DeleteCommodity"
const OperationCartGetCart = "/helloworld.v1.Cart/GetCart"
const OperationCartUpdateCommodity = "/helloworld.v1.Cart/UpdateCommodity"

type CartHTTPServer interface {
	AddCommodity(context.Context, *AddCommodityRequest) (*AddCommodityReply, error)
	ClearCart(context.Context, *ClearCartRequest) (*ClearCartReply, error)
	DeleteCommodity(context.Context, *DeleteCommodityRequest) (*DeleteCommodityReply, error)
	GetCart(context.Context, *GetCartRequest) (*GetCartReply, error)
	UpdateCommodity(context.Context, *UpdateCommodityRequest) (*UpdateCommodityReply, error)
}

func RegisterCartHTTPServer(s *http.Server, srv CartHTTPServer) {
	r := s.Route("/")
	r.POST("/add_commodity", _Cart_AddCommodity0_HTTP_Handler(srv))
	r.PUT("/update_commodity", _Cart_UpdateCommodity0_HTTP_Handler(srv))
	r.DELETE("/delete_commodity", _Cart_DeleteCommodity0_HTTP_Handler(srv))
	r.GET("/show_cart", _Cart_GetCart0_HTTP_Handler(srv))
	r.DELETE("/clear_cart", _Cart_ClearCart0_HTTP_Handler(srv))
}

func _Cart_AddCommodity0_HTTP_Handler(srv CartHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCommodityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartAddCommodity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCommodity(ctx, req.(*AddCommodityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCommodityReply)
		return ctx.Result(200, reply)
	}
}

func _Cart_UpdateCommodity0_HTTP_Handler(srv CartHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCommodityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartUpdateCommodity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCommodity(ctx, req.(*UpdateCommodityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCommodityReply)
		return ctx.Result(200, reply)
	}
}

func _Cart_DeleteCommodity0_HTTP_Handler(srv CartHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCommodityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartDeleteCommodity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCommodity(ctx, req.(*DeleteCommodityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCommodityReply)
		return ctx.Result(200, reply)
	}
}

func _Cart_GetCart0_HTTP_Handler(srv CartHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCartRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartGetCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCart(ctx, req.(*GetCartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCartReply)
		return ctx.Result(200, reply)
	}
}

func _Cart_ClearCart0_HTTP_Handler(srv CartHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearCartRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartClearCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearCart(ctx, req.(*ClearCartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearCartReply)
		return ctx.Result(200, reply)
	}
}

type CartHTTPClient interface {
	AddCommodity(ctx context.Context, req *AddCommodityRequest, opts ...http.CallOption) (rsp *AddCommodityReply, err error)
	ClearCart(ctx context.Context, req *ClearCartRequest, opts ...http.CallOption) (rsp *ClearCartReply, err error)
	DeleteCommodity(ctx context.Context, req *DeleteCommodityRequest, opts ...http.CallOption) (rsp *DeleteCommodityReply, err error)
	GetCart(ctx context.Context, req *GetCartRequest, opts ...http.CallOption) (rsp *GetCartReply, err error)
	UpdateCommodity(ctx context.Context, req *UpdateCommodityRequest, opts ...http.CallOption) (rsp *UpdateCommodityReply, err error)
}

type CartHTTPClientImpl struct {
	cc *http.Client
}

func NewCartHTTPClient(client *http.Client) CartHTTPClient {
	return &CartHTTPClientImpl{client}
}

func (c *CartHTTPClientImpl) AddCommodity(ctx context.Context, in *AddCommodityRequest, opts ...http.CallOption) (*AddCommodityReply, error) {
	var out AddCommodityReply
	pattern := "/add_commodity"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCartAddCommodity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartHTTPClientImpl) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...http.CallOption) (*ClearCartReply, error) {
	var out ClearCartReply
	pattern := "/clear_cart"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCartClearCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartHTTPClientImpl) DeleteCommodity(ctx context.Context, in *DeleteCommodityRequest, opts ...http.CallOption) (*DeleteCommodityReply, error) {
	var out DeleteCommodityReply
	pattern := "/delete_commodity"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCartDeleteCommodity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartHTTPClientImpl) GetCart(ctx context.Context, in *GetCartRequest, opts ...http.CallOption) (*GetCartReply, error) {
	var out GetCartReply
	pattern := "/show_cart"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCartGetCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartHTTPClientImpl) UpdateCommodity(ctx context.Context, in *UpdateCommodityRequest, opts ...http.CallOption) (*UpdateCommodityReply, error) {
	var out UpdateCommodityReply
	pattern := "/update_commodity"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCartUpdateCommodity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
